/**
 * BENGALI TTS PRE-PROCESSOR (V17 MASTERPLAN)
 * 
 * STRICT MODE: Filtering for MMS-TTS-BEN Vocabulary (Size 74) to prevent crashes.
 * Hacking the robotic Meta MMS VITS model to have comedic timing,
 * proper hoshonto pronunciation, and handle English loanwords natively.
 */

export function preprocessBengaliText(text: string): string {
    let processed = text;

    // 1. English-to-Bengali Phonetic Map 
    // MMS-BEN crashes or ignores English text. We must phoneticize common words FIRST.
    const englishMap: Record<string, string> = {
        "WhatsApp": "হোয়াটসঅ্যাপ",
        "YouTube": "ইউটিউব",
        "Internet": "ইন্টারনেট",
        "Facebook": "ফেসবুক",
        "Instagram": "ইনস্টাগ্রাম",
        "Comedy": "কমেডি",
        "Bong": "বং",
        "Bari": "বারি",
        "Hello": "হ্যালো",
        "Website": "ওয়েবসাইট",
        "AI": "এআই",
        "Podcast": "পডকাস্ট",
        "Android": "অ্যান্ড্রয়েড",
        "iPhone": "আইফোন"
    };

    // Case-insensitive replacement for loanwords
    for (const [eng, ben] of Object.entries(englishMap)) {
        const regex = new RegExp(eng, "gi");
        processed = processed.replace(regex, ben);
    }

    // 1.5 Number Normalization (Digit to Word)
    // The model struggles with raw digits (0-9). We map them to full Bengali words.
    // This improves prosody and prevents "English number" pronunciation.
    const numberMap: Record<string, string> = {
        '0': 'শূন্য', '1': 'এক', '2': 'দুই', '3': 'তিন', '4': 'চার',
        '5': 'পাঁচ', '6': 'ছয়', '7': 'সাত', '8': 'আট', '9': 'নয়',
        '০': 'শূন্য', '১': 'এক', '২': 'দুই', '৩': 'তিন', '৪': 'চার',
        '৫': 'পাঁচ', '৬': 'ছয়', '৭': 'সাত', '৮': 'আট', '৯': 'নয়'
    };
    
    // Replace all digits with their word equivalents surrounded by spaces
    processed = processed.replace(/[0-9০-৯]/g, (match) => ` ${numberMap[match]} `);
    
    // 1.6 Unit & Symbol Normalization (Added per user feedback)
    // Maps common symbols to spoken Bengali words for natural reading.
    const unitMap: Record<string, string> = {
        '%': ' শতাংশ ',
        '°C': ' ডিগ্রি সেলসিয়াস ',
        'km': ' কিলোমিটার ',
        'kg': ' কেজি ',
        'cm': ' সেন্টিমিটার ',
        'mm': ' মিলিমিটার ',
        '+': ' যোগ ',
        '=': ' সমান '
    };
    
    for (const [symbol, word] of Object.entries(unitMap)) {
        // Escape special regex chars if needed
        const regex = new RegExp(symbol.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), "g");
        processed = processed.replace(regex, word);
    }

    // Collapse multiple spaces generated by the above
    processed = processed.replace(/\s+/g, " ");

    // 2. Vocabulary Sanitization (CRITICAL FIX FOR CRASH 74)
    // The model ONLY supports: Bengali chars, Numbers, Space, -, _, ', —
    // It DOES NOT support: . , ! ? । (Danda)
    
    // Map pauses/stops/Danda to " - " (Dash is ID 67, supported, creates pause)
    processed = processed.replace(/[!,?।\.]/g, " - ");
    
    // Map other punctuation to spaces
    processed = processed.replace(/[;:"]/g, " ");

    // 3. Remove unsupported characters (Keep only allowed vocab)
    // Allowed: Bengali range (0980-09FF), Digits, Space, -, _, ', —
    // We replace anything else with space to be safe.
    processed = processed.replace(/[^ \u0980-\u09FF0-9\-_'—]/g, "");

    // 4. Cleanup spacing
    processed = processed.replace(/\s+/g, " ").trim();

    return processed;
}
