const fs=require('fs'); 
let c=fs.readFileSync('client/src/pages/SocialDownloaderPage.tsx','utf8'); 
c=c.replace(/Ã¢â€â‚¬/g,'—');
c=c.replace(/Ã¢â‚¬â€/g,'—');
c=c.replace(/Ã¢â€ Â/g,'←');
c=c.replace(/Ã°Å¸Å¡â‚¬/g,'🚀');
c=c.replace(/Ã‚Â©/g,'©');
c=c.replace(/Ã¢â‚¬Â¢/g,'•');
c=c.replace(/Ã¢â€ â€™/g,'→');
c=c.replace(/Ã¢Å“â€¦/g,'✅');
c=c.replace(/Ã°Å¸â€Å½/g,'🔍');
c=c.replace(/Ã°Å¸â€œÂ/g,'📝');
c=c.replace(/Ã°Å¸Å½Â¥/g,'🎬');
c=c.replace(/Ã°Å¸â€ºÂ¡Ã¯Â¸Â/g,'🛡️');
c=c.replace(/Ã°Å¸â€ºÂ /g,'🛠️');
c=c.replace(/Ã°Å¸â€ºÂ /g,'🛠️');
c=c.replace(/Ã°Å¸â€ºÂ/g,'🛠️');
c=c.replace(/Ã¢Ëœï¿½/g,'☁️');
c=c.replace(/Ã¢â€Â/g,'←');
fs.writeFileSync('client/src/pages/SocialDownloaderPage.tsx',c);
console.log('Fixed using robust replacement script!');
